### ISSUE TITLE
Loot sheet cannot be opened after assigning it

### ISSUE THREAD

**Issue by TiloBuechsenschuss** [Djphoenix719/FVTT-PF2EToolbox#39] opened 2021-05-05 13:39 UTC
**Describe the bug**
Sheets of Loot actors with the assigned sheet pf2e-toolbox.LootApp cannot be opened.

**To Reproduce**
Set an actor's sheet to pf2e-toolbox.LootApp in PF2E 1.14.0

**Expected behavior**
The sheet should open when double-clicking the actor on the canvas or clicking the actor in the Actors directory.

**Additional context**
Probably related to the updates of the PF2E system recently. Maybe also related to issue #37 ?

**Comment by Djphoenix719** [comment] 2021-05-05 16:42
Thanks @TiloBuechsenschuss - yes this is likely a duplicate of #37 and related to the PF2E update. I will have some time to take a look at it today.

**Closed as completed** 2021-05-05 21:24 UTC
Labels: bug

**Comment by TiloBuechsenschuss** [comment] 2021-05-05 21:51
Thanks so much for the quick fix! :-)
