### ISSUE TITLE
PF2 Toolbox 1.7.9 - the Settings modal dialog doesn't open

### ISSUE THREAD

**Issue by apoapostolov** [Djphoenix719/FVTT-PF2EToolbox#50] opened 2021-07-11 16:24 UTC
Tested with no mods (other than libwrapper just in case).

**Comment by Djphoenix719** [comment] 2021-07-11 16:40
Hey @apoapostolov - can you unistall and reinstall Toolbox to verify this for me. I am unable to reproduce this with version 1.7.9 locally.

**Comment by apoapostolov** [comment] 2021-07-11 17:56
Yes, did so. Same behavior. Tested with Culprit and no mods.

**Comment by Djphoenix719** [comment] 2021-07-11 18:06
Do you see any errors in the console?

**Comment by apoapostolov** [comment] 2021-07-11 21:28
![image](https://user-images.githubusercontent.com/4083812/125210358-04edab80-e2a8-11eb-8282-e84faea249f2.png)

d {description: undefined, fileName: undefined, lineNumber: undefined, endLineNumber: undefined, message: "An error occurred while rendering SettingsApp 148:…s/settings-app/tabs/About.html could not be found", …}description: undefinedendLineNumber: undefinedfileName: undefinedlineNumber: undefinedmessage: "An error occurred while rendering SettingsApp 148: The partial modules/pf2e-lootgen/templates/settings-app/tabs/About.html could not be found"name: "Error"number: undefinedstack: "Error: An error occurred while rendering SettingsApp 148: The partial modules/pf2e-lootgen/templates/settings-app/tabs/About.html could not be found↵    at Object.h (http://localhost:30000/scripts/handlebars.min.js:27:18644)↵    at Object.c [as invokePartial] (http://localhost:30000/scripts/handlebars.min.js:27:15036)↵    at Object.eval [as main] (eval at createFunctionContext (http://localhost:30000/scripts/handlebars.min.js:29:1808), <anonymous>:11:28)↵    at c (http://localhost:30000/scripts/handlebars.min.js:27:15429)↵    at d (http://localhost:30000/scripts/handlebars.min.js:27:15744)↵    at e (http://localhost:30000/scripts/handlebars.min.js:28:22748)↵    at renderTemplate (http://localhost:30000/scripts/foundry.js:3627:10)↵    at async SettingsApp._renderInner (http://localhost:30000/scripts/foundry.js:2213:16)↵    at async SettingsApp._renderInner (http://localhost:30000/scripts/foundry.js:2740:18)↵    at async SettingsApp._render (http://localhost:30000/scripts/foundry.js:2048:19)"__proto__: Error
    at Object.<anonymous> (http://localhost:30000/scripts/handlebars.min.js:27:5241)
    at b (http://localhost:30000/scripts/handlebars.min.js:27:330)
    at Object.<anonymous> (http://localhost:30000/scripts/handlebars.min.js:27:2069)
    at b (http://localhost:30000/scripts/handlebars.min.js:27:330)
    at Object.<anonymous> (http://localhost:30000/scripts/handlebars.min.js:27:1435)
    at b (http://localhost:30000/scripts/handlebars.min.js:27:330)
    at Object.<anonymous> (http://localhost:30000/scripts/handlebars.min.js:27:792)
    at b (http://localhost:30000/scripts/handlebars.min.js:27:330)
    at http://localhost:30000/scripts/handlebars.min.js:27:417
    at http://localhost:30000/scripts/handlebars.min.js:27:422
(anonymous) @ foundry.js:2006
Promise.catch (async)
render @ foundry.js:2004
onClickSubmenuWrapper @ colorSetting.js:20
🎁SettingsConfig.prototype._onClickSubmenu#0 @ libWrapper-wrapper.js:160
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by Djphoenix719** [comment] 2021-07-11 21:41
@apoapostolov Ok this should be fixed in 1.7.11

**Comment by Djphoenix719** [comment] 2021-07-11 21:41
Thanks!

**Closed as completed by Djphoenix719** 2021-07-11 21:41 UTC
Labels: bug
